# For more information: https://laravel.com/docs/sail
version: "3"
services:
    copon-cms:
        build:
            context: .
            dockerfile: Dockerfile            
        ports:
            - "8000:8000"
