# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel:
        container_name: coupon-cms-laravel
        build:
            args:
                user: sammy
                uid: 1000
            context: .
            dockerfile: Dockerfile       
        environment:
            DB_HOST: pgsql
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - .:/var/www
        networks:
            - sail
        depends_on:            
            - pgsql
    pgsql:
        image: postgres:13
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'sailpostgresql:/var/lib/postgresql/data'
        networks:
            - sail
    nginx:
        image: nginx:alpine
        container_name: coupon-cms-nginx
        restart: unless-stopped
        ports:
        - 8000:80
        volumes:
        - .:/var/www
        - ./nginx:/etc/nginx/conf.d
        networks:
        - sail
networks:
    sail:
        driver: bridge
volumes:
    sailpostgresql:
       driver: local
    
