# For more information: https://laravel.com/docs/sail
version: "3"
services:
    postgres:
        image: postgres
        environment:
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
            POSTGRES_DB: '${DB_DATABASE}'
            PGDATA: /data/postgres
        volumes:
            - sailpostgres:/data/postgres
        ports:
            - "5432:5432"
        restart: unless-stopped
volumes:
    sailpostgres:
        driver: local